/** SAW049 — Seed defaults for roster matching rules (AbilityAPP schadsDefault pattern). */
import type { RosterRuleRecord } from './rosterRules';

export function defaultRosterRules(actor = 'system'): RosterRuleRecord[] {
  const base = {
    enabled: true,
    effectiveFrom: null as string | null,
    effectiveTo: null as string | null,
    updatedBy: actor,
    updatedAt: null as string | null,
    created: null as string | null,
    deletedAt: null as string | null,
  };

  return [
    {
      ...base,
      id: 'rule-not-excluded',
      ruleType: 'not_excluded',
      name: 'Not excluded',
      description: 'Worker must not have hr_exclude = Y.',
      enforcement: 'blocking',
      priority: 10,
      parameters: {},
    },
    {
      ...base,
      id: 'rule-not-on-leave',
      ruleType: 'not_on_leave',
      name: 'Not on approved leave',
      description: 'Worker must not have approved leave overlapping the shift window.',
      enforcement: 'blocking',
      priority: 20,
      parameters: {},
    },
    {
      ...base,
      id: 'rule-no-time-clash',
      ruleType: 'no_time_clash',
      name: 'No overlapping shift',
      description: 'Worker must not already be assigned to an overlapping active shift.',
      enforcement: 'blocking',
      priority: 30,
      parameters: {},
    },
    {
      ...base,
      id: 'rule-credentials-held',
      ruleType: 'credentials_held',
      name: 'Required credentials held',
      description: 'Worker must hold every credential required by the shift for the shift window.',
      enforcement: 'blocking',
      priority: 40,
      parameters: {},
    },
    {
      ...base,
      id: 'rule-gender-preference',
      ruleType: 'gender_preference',
      name: 'Gender preference',
      description: 'When the shift has a gender preference, worker gender must match.',
      enforcement: 'blocking',
      priority: 50,
      parameters: {},
    },
    {
      ...base,
      id: 'rule-min-break-between',
      ruleType: 'min_break_between_shifts',
      name: 'Min break between shifts (10h)',
      description: 'Minimum rest hours between adjacent shifts (reduced after sleepover).',
      enforcement: 'blocking',
      priority: 60,
      parameters: { minBreakHours: 10, sleepoverReducedBreakHours: 8 },
    },
    {
      ...base,
      id: 'rule-max-weekly-hours',
      ruleType: 'max_weekly_hours',
      name: 'Max weekly / fortnightly hours',
      description: 'Cap assigned hours in the week / fortnight containing the vacant shift.',
      enforcement: 'blocking',
      priority: 70,
      parameters: { maxWeeklyHours: 38, maxFortnightlyHours: 76, maxFourWeeklyHours: 152 },
    },
    {
      ...base,
      id: 'rule-max-consecutive-days',
      ruleType: 'max_consecutive_days',
      name: 'Max consecutive days (6)',
      description: 'Block assignment that would create more than N consecutive work days.',
      enforcement: 'warning',
      priority: 80,
      parameters: { maxConsecutiveDays: 6, minDaysOffPerWeek: 2 },
    },
    {
      ...base,
      id: 'rule-max-shift-hours',
      ruleType: 'max_shift_hours',
      name: 'Max shift length',
      description: 'Reject (or warn) when the vacant shift itself exceeds configured length caps.',
      enabled: false,
      enforcement: 'warning',
      priority: 90,
      parameters: {
        standardMaxHours: 8,
        extendedMaxHours: 10,
        requiresWrittenAgreement: true,
        absoluteMaxHours: 12,
      },
    },
  ];
}
